apiVersion: apps/v1
kind: Deployment
metadata:
  name: special-seminar-surrogate
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: special-seminar-surrogate
  template:
    metadata:
      labels:
        app: special-seminar-surrogate
    spec:
      containers:
      - image: koyamaso/special-seminar-surrogate:0.1.2
        name: special-seminar-surrogate
        env:
        - name: REDIS_HOST
          value: "127.0.0.1"
        - name: DNS_SERVER
          value: "pdns-svc.default.svc.cluster.local"
        - name: PROXY_HOST
          value: "0.0.0.0"
        - name: PROXY_PORT
          value: "8082"
        ports:
        - containerPort: 8082
          protocol: TCP
      - image: redis:latest 
        name: redis 
        ports:
        - containerPort: 6379