apiVersion: v1
kind: Service
metadata:
  name: surrogate-svc
spec:
  type: LoadBalancer
  loadBalancerIP: "34.66.73.185"
  ports:
  - port: 80
    targetPort: 8082
    name: http
    protocol: TCP
  selector:
    app: special-seminar-surrogate