apiVersion: apps/v1
kind: Deployment
metadata:
  name: special-seminar-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: special-seminar-api
  template:
    metadata:
      labels:
        app: special-seminar-api
    spec:
      containers:
      - image: koyamaso/special-seminar-api:0.1.4
        name: special-seminar-api
        ports:
        - containerPort: 50051