apiVersion: apps/v1
kind: Deployment
metadata:
  name: special-seminar-gateway
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: special-seminar-gateway
  template:
    metadata:
      labels:
        app: special-seminar-gateway
    spec:
      volumes:
        - name: envoy-gateway
          configMap:
            name: central-gateway-configmap
        - name: tls-cert 
          secret:
            secretName: tls-central 
            items:
            - key: tls.crt
              path: beta-spesemi2019.crt
            - key: tls.key 
              path: beta-spesemi2019.key
      containers:
      - image: envoyproxy/envoy:latest
        name: envoy
        command:
          - "/usr/local/bin/envoy"
        args:
          - "--config-path /etc/envoy/envoy.yaml"
        volumeMounts:
          - name: envoy-gateway
            mountPath: /etc/envoy
          - name: tls-cert 
            mountPath: /etc
        ports:
          - containerPort: 80
          - containerPort: 8081