apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: central-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /foo(/|$)(.*)
        backend:
          serviceName: web-svc
          servicePort: 80