apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: central-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: web-svc
          servicePort: 8080
      - backend:
          serviceName: api-svc
          servicePort: 50051
        path: /grpc(/|$)(.*)