apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: central-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /foo
        backend:
          serviceName: web-svc
          servicePort: 8080