apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: central-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /foo
        backend:
          serviceName: web-svc
          servicePort: 80