apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
    app: special-seminar-web
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: special-seminar-web