apiVersion: apps/v1
kind: Deployment
metadata:
  name: special-seminar-lazy-ns
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: special-seminar-lazy-ns
  template:
    metadata:
      labels:
        app: special-seminar-lazy-ns
    spec:
      containers:
      - image: koyamaso/special-seminar-lazy-ns:1.0.0
        name: special-seminar-lazy-ns
        env:
        - name: TARGET_IP
          value: "34.66.73.185"
        ports:
        - containerPort: 53
          protocol: UDP