apiVersion: v1
kind: Service
metadata:
  name: lazy-ns-svc
spec:
  type: LoadBalancer
  ports:
  - port: 53
    targetPort: 53
    name: dns
    protocol: UDP
  selector:
    app: special-seminar-lazy-ns